### ISSUE TITLE
Seems we missed the prompt template in repo

### ISSUE THREAD

**Issue by JasonZhu1313** [agent-husky/Husky-v1#1]
Hey, thanks for great work and I am interested to try the code, but looks like all the initial prompt template are missing: ex. HUSKY_ACTION_GENERATOR_MISTRAL_PROMPT, HUSKY_ACTION_GENERATOR_TULU_PROMPT, HUSKY_ACTION_GENERATOR_PROMPT

**Comment by danieljkim0118** [comment]
The prompts have been added to the repo. Thanks for pointing this out!!
